dist: xenial
language: python
arch:
   - amd64
   - ppc64le
matrix:
  include:
    # Only run lint on a single 3.x
    - env: TOX_SUFFIX="lint"
      python: "3.7"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
# Disable version  pypy
jobs:
  exclude:
  - arch: ppc64le
    python: "pypy3"

before_install:
  - openssl version
  - sudo apt-get install libgnutls28-dev

install:
  - pip install tox-travis codecov
  - if [[ $TOX_SUFFIX != 'lint' ]]; then python setup.py install ; fi
script:
  - tox
after_success:
  - codecov
